### ISSUE TITLE
Intentional unpublish?

### ISSUE THREAD

**Issue by danprince** [roobie/mori-ext#1]
Has this package been intentionally unpublished from NPM? It no longer shows up: https://www.npmjs.com/package/mori-ext.

It would be a real shame if someone hijacks the name.

**Comment by roobie** [comment]
Hi!
Yes, I'm sorry to say that it is intentional. This is due to events detailed [here](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.wrdw9sux6).

I sympathize with the author of the article and agree with the opinions stated there.

Thanks for your interest. Feel free continue using this module by installing directly from github:

`npm install git+https://github.com/roobie/mori-ext/`

I'll update the README with this info before closing this issue.

**Comment by roobie** [comment]
I've come to reason regarding this issue. Maybe it was silly of me to unpublish the package. I'll republish it in hopes that more people will use `mori` and realise that immutability is good, and function bind syntax would be awesome to have in standard JS.

**Comment by roobie** [comment]
Once again, `mori-ext` is available on npmjs.org https://www.npmjs.com/package/mori-ext
